name: sejong_catch
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter # Flutter 프레임워크 기본

  cupertino_icons: ^1.0.8 # iOS 스타일 아이콘

dev_dependencies:
  flutter_test:
    sdk: flutter # Flutter 테스트 도구

  flutter_lints: ^5.0.0 # 코드 린팅 및 스타일 검사

  # 상태 관리 & 아키텍처
  provider: ^6.1.5+1 # 상태 관리 라이브러리
  freezed: ^3.2.0 # 불변 데이터 클래스 생성
  json_serializable: ^6.11.1 # JSON 직렬화 자동 생성

  # 라우팅 & 네비게이션 
  go_router: ^16.2.1 # 라우팅 및 네비게이션 관리

  # 네트워크 & 인증
  dio: ^5.9.0 # HTTP 클라이언트
  retrofit: ^4.7.2 # REST API 클라이언트 생성
  flutter_secure_storage: ^9.2.4 # 안전한 데이터 저장

  # UI/UX 레이아웃
  flutter_screenutil: ^5.9.3 # 화면 크기 및 해상도 대응
  cached_network_image: ^3.4.1 # 네트워크 이미지 캐싱
  shimmer: ^3.0.0 # 로딩 애니메이션 효과
  smooth_page_indicator: ^1.2.1 # 페이지 인디케이터 UI

  # 리스트 & 데이터 표시
  infinite_scroll_pagination: ^5.1.1 # 무한 스크롤 페이징
  pull_to_refresh: ^2.0.0 # 당겨서 새로고침 UI

  # 알림 & 실시간
  firebase_messaging: ^16.0.1 # 푸시 알림 서비스
  awesome_notifications: ^0.10.1 # 로컬 알림 생성
  web_socket_channel: ^3.0.3 # 웹소켓 통신

  # 분석 & 안정성
  firebase_analytics: ^12.0.1 # 앱 분석 도구
  firebase_crashlytics: ^5.0.1 # 크래시 리포팅

  # 차트 & 데이터 시각화 (운영자용)
  syncfusion_flutter_charts: ^31.1.17 # 차트 위젯 라이브러리


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
